#!/usr/bin/env python3
"""
Generate HTML summary report artifact for Nexus.
"""

from pathlib import Path

root = Path(__file__).parent
output_path = root / "generated_report.html"

title = "Nexus"
description = "A full-featured media workspace with database persistence, rich media players, omnisearch, sorting, and metadata editing."
bullets = [
    "Upload any file (audio, video, images, PDFs, docs, code, binary archives)",
    "Custom metadata editor (title, filename, tags, date/time, category, author, status, rating, custom properties)",
    "HTML5 video player, Web Audio API frequency visualizer, image lightbox, markdown/code reader, and PDF viewer",
    "Multi-criteria ordering by date, name, filename, size, type, and rating",
    "Real-time omnisearch across all metadata fields, status chips, dynamic tag cloud, date/size presets",
    "Single item, batch selection, and all-entries deletion with safety confirmation and undo stack",
    "Database file persistence with REST backend API server",
]

html = f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>{title}</title>
  <style>
    body {{ font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif; margin: 2rem; line-height: 1.6; color: #0f172a; background-color: #f8fafc; }}
    .card {{ max-width: 800px; margin: 0 auto; padding: 2rem; background: #ffffff; border: 1px solid #e2e8f0; border-radius: 12px; box-shadow: 0 8px 24px rgba(0,0,0,0.06); }}
    h1 {{ margin-bottom: 0.5rem; color: #1e293b; }}
    p {{ color: #475569; }}
    ul {{ padding-left: 1.2rem; margin: 1.5rem 0; }}
    li {{ margin-bottom: 0.5rem; color: #334155; }}
    .footer {{ font-size: 0.85rem; color: #94a3b8; margin-top: 2rem; border-top: 1px solid #f1f5f9; padding-top: 1rem; }}
  </style>
</head>
<body>
  <div class="card">
    <h1>{title}</h1>
    <p>{description}</p>
    <ul>
"""

for item in bullets:
    html += f"      <li>{item}</li>\n"

html += """    </ul>
    <p class="footer">Generated by generate_report.py in nexus/.</p>
  </div>
</body>
</html>
"""

output_path.write_text(html, encoding="utf-8")
print(f"Report written to {output_path}")
